# Uncomment the next line to define a global platform for your project
platform :ios, '13'

target 'Square Waves' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Square Waves
  pod 'SSZipArchive'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'OpenSSL-Universal'
end
