# Uncomment the next line to define a global platform for your project
platform :ios, '13'

target 'Square Waves' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Square Waves
  pod 'SSZipArchive'
  pod 'UnrarKit'
  pod 'LzmaSDK-ObjC', :inhibit_warnings => true
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'openssl-ios-bitcode'
end
