# Uncomment the next line to define a global platform for your project
platform :ios, '13'

target 'Square Wave' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Square Wave
  pod 'SSZipArchive'
  pod 'MarqueeLabel'
end
